spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_flyway?autoReconnect=true&useSSL=false
    username: web_app
    password: hogehoge
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
server:
  port: 8080
