spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_flyway?autoReconnect=true&useSSL=false
    username: web_app
    password: hogehoge
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
